#----------------------- Server Port---------------------------------------
server.port=${PORT}


# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7rllnsm0tmc738dddl0-a.oregon-postgres.render.com:5432/student_form_4jsg
spring.datasource.username=student_form_4jsg_user
spring.datasource.password=W3lQtm4DzaB1TyDmdzuiCypsEXEPDEcA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000


# JWT
spring.security.user.name=admin
spring.security.user.password=admin
spring.main.allow-circular-references=true

# MAIL ✅
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

